src/Entity/Trick.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @UniqueEntity("name",fields={"name"}, message="Ce nom existe deja")
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Le nom est obligatoire")
     * @Assert\Length(min=3, minMessage="Le nom doit avoir au moins 3 caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="La descritpion est obligatoire")
     * @Assert\Length(min=20, minMessage="La description doit avoir au moins 20 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="trick")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $pictures;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="trick", orphanRemoval=true,cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mainPicture;


    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->comments = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(?string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                "label" => "Name",
                "attr"  => ['placeholder' => 'Please enter a name']
            ])
            ->add('description', TextareaType::class, [
                "label" => "Description",
                "attr"  => ["placeholder" => "Please enter a description"]
            ])
            ->add('mainPicture', FileType::class, [
                'required' => false,
                'multiple' => false,
                'mapped' => false
            ])
            ->add('category', EntityType::class, [
                "label" => "Catégory",
                "placeholder" => "-- Choose category --",
                "class" => Category::class,
                "choice_label" => function (Category $category) {
                    return strtoupper($category->getName());
                }
            ])
            ->add('pictures', FileType::class, [
                "label" => "Pictures",
                "multiple" => true,
                "mapped" => false,
                'required' => false
            ])
            ->add('videos', CollectionType::class, [
                'label' => "Videos",
                'entry_type' => VideoType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;


use App\Entity\Trick;
use App\Entity\Comment;
use App\Entity\Picture;
use App\Form\TrickType;
use App\Form\CommentType;
use App\Service\TrickService;
use App\Repository\TrickRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TrickController extends AbstractController
{

    /**
     * @var TrickRepository
     */
    private $repository;


    public function __construct(TrickRepository $repository)
    {
        $this->repository = $repository;
    }


    /**
     * @Route("/{category_slug<^[a-zA-Z][a-z_A-Z-]+$>}/{slug}", name="trick_show", priority=-1)
     */
    public function show($category_slug, $slug, Request $request, EntityManagerInterface $em)
    {
        $trick = $this->repository->findOneBy(["slug" => $slug]);

        if (!$trick) {
            throw $this->createNotFoundException("
            This trick does not exist");
        }
        if ($category_slug !== $trick->getCategory()->getSlug()) {
            throw $this->createNotFoundException("
            This category does not exist");
        }

        $comment = new Comment;
        $currentPage = 1;
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setTrick($trick);
            $comment->setAuthor($this->getUser());
            $em->persist($comment);
            $em->flush();
            return $this->redirectToRoute('trick_show', [
                'category_slug' => $trick->getCategory()->getSlug(),
                'slug'          => $trick->getSlug()
            ]);
        }

        return $this->render("trick/show.html.twig", ['trick' => $trick, "formView" => $form->createView(), 'currentPage' => $currentPage]);
    }


    /**
     * @Route("/admin/trick/create" , name="trick_create", methods={"GET","POST"})
     */
    public function create(Request $request, EntityManagerInterface $em, TrickService $trickService)
    {
        $trick = new Trick;

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $trickService->valide($form, $trick);

            $em->persist($trick);
            $em->flush();
            $this->addFlash("success", "Trick successfully created!");
            return $this->redirectToRoute('home');
        }


        $formView = $form->createView();

        return $this->render("trick/create.html.twig", ['formView' => $formView]);
    }


    /**
     * @Route("/admin/trick/{id<\d+>}/edit" , name="trick_edit", methods={"GET", "PUT"})
     */
    public function edit(Request $request, Trick $trick, EntityManagerInterface $em, TrickService $trickService)
    {
        $form = $this->createForm(TrickType::class, $trick, [
            'method' => 'PUT'
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $trickService->valide($form, $trick);

            $em->flush();
            $this->addFlash("success", "Trick successfully updated !");
            return $this->redirectToRoute('trick_show', [
                'category_slug' => $trick->getCategory()->getSlug(),
                'slug'          => $trick->getSlug()
            ]);
        }

        $formView = $form->createView();

        return $this->render("trick/edit.html.twig", ['formView' => $formView, 'trick' => $trick]);
    }

    /**
     * @Route("/page/trick/{page<\d+>}" , name="trick_paginated")
     * @return Response
     */
    public function tricksPaginated($page): Response
    {
        $limit = 12;
        $currentPage = $page;
        $total = $this->repository->getTotalTricks();

        $tricks = $this->repository->getPaginatedTricks($currentPage, $limit);
        $isLast = $this->repository->isLast($currentPage, ceil($total / $limit));

        return $this->render("trick/cardList.html.twig", [
            "tricks" => $tricks,
            "total" => $total,
            "currentPage" => $currentPage,
            "limit" => $limit,
            "isLast" => $isLast
        ]);
    }

    /**
     * 
     * @Route("/admin/trick/{id<\d+>}/delete" , name="trick_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Trick $trick, EntityManagerInterface $em)
    {
        if ($this->isCsrfTokenValid("delete" . $trick->getId(), $request->request->get('_token'))) {

            // supprime les photos ddu dossier local
            foreach ($trick->getPictures() as $picture) {
                $this->deletePictures($picture->getName());
            }
            if ($trick->getMainPicture())
                $this->deletePictures($trick->getMainPicture());

            $em->remove($trick);
            $em->flush();
            $this->addFlash("success", "Trick successfully deleted !");
        }

        return $this->redirectToRoute("home");
    }


    /**
     * 
     * @Route("/admin/image/{id<\d+>}/delete" , name="trick_delete_picture", methods="DELETE")
     */
    public function deletePicture(Picture $picture, Request $request, EntityManagerInterface $em)
    {
        $data = json_decode($request->getContent(), true);

        // on verifie Token
        if ($this->isCsrfTokenValid('delete' . $picture->getId(), $data['_token'])) {

            // on supprime du dossier local
            $this->deletePictures($picture->getName());

            // on supprime de la BDD
            $em->remove($picture);
            $em->flush();

            // on répond en Json
            return new JsonResponse(['success' => 1]);
        } else {
            return new JsonResponse(['error' => 'Token Invalide'], 400);
        }
    }

    private function deletePictures($picture)
    {
        // on supprime du dossier local
        unlink($this->getParameter('pictures_directory') . '/' . $picture);
    }
}

templates/trick/_card.html.twig
<div class="col">
	<div class="card shadow-sm">
		{% if trick.mainPicture == null %}
			<img class="img-fluid" src="{{asset('img/home.jpg')}}" alt="">
		{% else %}
			<img class="img-fluid" src="{{ asset('uploads/' ~ trick.mainPicture )}}"/>
		{% endif %}
		<title>{{ trick.name}}</title>
	</div>
	<div class="card-body">
		<h3 class="text-center">{{ trick.name|upper}}</h3>
		<div class="d-flex justify-content-between align-items-center">
			<div class="btn-group">
				<a href="{{ path('trick_show',{ "category_slug" : trick.category.slug ,"slug" : trick.slug }) }}" type="button" class="btn btn-sm btn-outline-primary">View</a>
			</div>
			{% if app.user %}
				<div>
					<a href="{{ path('trick_edit',{"id" : trick.id })}}" type="button" class="btn btn-sm font-primary">
						<i class="fas fa-pen "></i>
					</a>

					{% include "trick/form/_card_delete.html.twig" %}

				</div>
			{% endif %}
		</div>
	</div>
</div>

templates/trick/cardList.html.twig
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
	{% for trick in tricks %}
		{{ include('trick/_card.html.twig') }}
	{% endfor %}
</div>

{% if isLast == false %}
	<span class="d-none">
		{{ path('trick_paginated', {'page': currentPage + 1}) }}
	</span>
{% else %}
	<span class="d-none"></span>
{% endif %}

templates/trick/create.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter une figure
{% endblock %}

{% block body %}
	<div class="mt-5 ">
		<h1 class="text-center">Add Trick</h1>

		{% include "trick/form/_form.html.twig" %}

	</div>
{% endblock %}


{% block javascript %}
	<script src="{{ asset('js/medias.js')}}"></script>
{% endblock %}

templates/trick/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modifier une figure
{% endblock %}

{% block body %}
	<div class="mt-5 ">
		<h1 class="text-center">Update trick</h1>

		{% include "trick/form/_form.html.twig" with {submitButtonText:"Update"}%}
		<div class="text-center mb-3 text-primary" id="deleteButton">
			Delete
			{% include 'trick/form/_card_delete.html.twig' %}
		</div>

	</div>
{% endblock %}

{% block javascript %}
	<script src="{{ asset('js/medias.js') }}"></script>
{% endblock %}

templates/trick/list.html.twig
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
	{% for trick in tricks %}
		{{ include('trick/_card.html.twig') }}
	{% endfor %}
</div>

{% if isLast == false %}
	<span class="d-none">
		{{ path('trick_paginated', {'page': currentPage + 1}) }}
	</span>
{% else %}
	<span class="d-none"></span>
{% endif %}

templates/trick/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Figure
	{{ trick.name }}
{% endblock %}

{% block body %}

	<div class="container py-5">
		<div class="row text-center mb-5">
			<h1 class="mb-5">{{ trick.name|upper}}</h1>
			<div class="col-lg-10 mx-auto row">
				<div id="mainPicture">
					{% if app.user %}
						<div>
							<a href="{{ path('trick_edit',{"id" : trick.id })}}" type="button" class="btn btn-sm font-primary">
								<i class="fas fa-pen "></i>
							</a>

							{% include "trick/form/_card_delete.html.twig" %}

						</div>
					{% endif %}
					{% if trick.mainPicture == null %}
						<img class="img-fluid" src="{{asset('img/home.jpg')}}" alt="">
					{% else %}
						<img class="img-fluid" src="{{ asset('uploads/' ~ trick.mainPicture )}}"/>
					{% endif %}
				</div>
				<div class="d-lg-none">
					<p class="text-center">
						<button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse" aria-expanded="false" aria-controls="collapse">
							Voir les médias
						</button>
					</p>
					<div class="collapse mb-4 text-center" id="collapse">
						{% for picture in trick.pictures %}
							<div class="col">
								<img src="{{ asset('uploads/' ~ picture.name ) }}" alt="Image" class="img-thumbnail">
							</div>
						{% endfor %}
						{% for video in trick.videos %}
							<div class="col">
								<iframe width="100%" height="300" src="{{ video.url }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						{% endfor %}
					</div>
				</div>
				<div class="row pr-0">
					<div class="col-lg-7  d-none d-lg-block">
						{% include "medias/picturesCarousel.html.twig" %}
					</div>
					<div class="col-lg-5  d-none d-lg-block p-0">
						{% include "medias/videosCarousel.html.twig" %}
					</div>
				</div>
				<div>
					<p class="text-start col-8 mx-auto">{{trick.description|nl2br}}</p>
				</div>
				<div class="text-start">
					<p>Category :
						<span class="badge rounded-pill bg-primary">{{ trick.category.name|upper}}</span>
					</p>
					<div class="row">
						<p class="text-muted col-md-6">
							Ecrit le :
							{{ trick.createdAt|date('Y-m-d à h:i')}}
						</p>
						<p class="text-muted col-md-6 text-end">
							{{ (trick.updatedAt != trick.createdAt) ? 'Modifé le : ' ~ trick.updatedAt | date('Y-m-d à h:i')}}</p>
					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="container">
		<div class="be-comment-block">
			<h2 class="comments-title">Comments</h2>

			{{ render(path('comment_paginated', {trickId: trick.id, page: 1})) }}
			{% if (trick.comments|length) > 0 %}
				<div class="text-center mt-4">
					<a type="button" class="btn btn-outline-primary" id="load" href="#">Load More</a>
				</div>
			{% endif %}

			{% if app.user %}
				{{ form_start(formView)}}
				{{ form_errors(formView)}}
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							{{ form_row(formView.content)}}
						</div>
					</div>
					<button class="btn btn-primary pull-right" type="submit">Send</button>
				</div>
				{{ form_end(formView)}}
			{% else %}
				<div class="mt-5 text-center">
					<p class="d-inline">You must be logged in to leave a comment
					</p>
					<a href="{{path('security_login')}}" class="d-inline text-primary">Log in</a>
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}
{% block javascript %}
	{{ parent() }}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js" integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ==" crossorigin="anonymous"></script>
	<script src="{{ asset('js/load.js')}}"></script>
{% endblock %}